final:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wheel_front_left_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_front_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_front_right_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_front_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_back_left_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_back_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  coupler_back_right_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: coupler_back_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  coupler_front_left_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: coupler_front_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  coupler_front_right_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: coupler_front_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  coupler_back_left_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: coupler_back_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_back_right_joint_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_back_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
